[package]
name = "mr_persistence"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mr_utils_lib = { path = "../../libs/utils_lib" }

actix-web = "4.0.0-beta.13"
anyhow = "1.0.47"
bincode = "1.3.3"
env_logger = "0.8.1"
futures = "0.3.17"
log = "0.4.14"
sentry = "0.23.0"
serde = "1.0.68"
serde_derive = "1.0.68"
