# Reference: https://agones.dev/site/docs/reference/fleet/
apiVersion: "agones.dev/v1"
kind: GameServer
# Fleet Metadata
# https://v1-20.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#objectmeta-v1-meta
metadata:
  generateName: "mr-server-"
spec:
  ports:
    - name: MUDDLE_LISTEN_PORT
      # portPolicy has three options:
      # - "Dynamic" (default) the system allocates a free hostPort for the gameserver, for game clients to connect to
      # - "Static", user defines the hostPort that the game client will connect to. Then onus is on the user to ensure that the
      # port is available. When static is the policy specified, `hostPort` is required to be populated
      # - "Passthrough" dynamically sets the `containerPort` to the same value as the dynamically selected hostPort.
      #      This will mean that users will need to lookup what port has been opened through the server side SDK.
      portPolicy: Passthrough
      # protocol being used. Defaults to UDP. TCP and TCPUDP are other options
      # - "UDP" (default) use the UDP protocol
      # - "TCP", use the TCP protocol
      # - "TCPUDP", uses both TCP and UDP, and exposes the same hostPort for both protocols.
      #       This will mean that it adds an extra port, and the first port is set to TCP, and second port set to UDP
      protocol: TCPUDP
  health:
    # Number of seconds after the container has started before health check is initiated. Defaults to 5 seconds
    initialDelaySeconds: 5
    # If the `Health()` function doesn't get called at least once every period (seconds), then
    # the game server is not healthy. Defaults to 5
    periodSeconds: 5
    # Minimum consecutive failures for the health probe to be considered failed after having succeeded.
    # Defaults to 3. Minimum value is 1
    failureThreshold: 3
  # Parameters for game server sidecar
  sdkServer:
    logLevel: Info
    grpcPort: 9357
    httpPort: 9358
  # [Stage:Alpha]
  # [FeatureFlag:PlayerTracking]
  # Players provides the configuration for player tracking features.
  # Commented out since Alpha, and disabled by default
  # players:
  #   # set this GameServer's initial player capacity
  #   initialCapacity: 10
  # Pod template configuration
  # https://v1-20.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podtemplate-v1-core
  template:
    metadata:
      labels:
        app: mr
    spec:
      containers:
        - name: mr-server
          image:  mvlabat/mr_server
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "1"
            limits:
              memory: "64Mi"
              cpu: "1"
