[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"
bevy_egui = "0.20"
bevy-inspector-egui = "0.18"
bevy_mod_picking = "0.12"
bevy_transform_gizmo = "0.6"
