[package]
name = "mr_server"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
use-udp = ["mr_server_lib/use-udp"]
use-webrtc = ["mr_server_lib/use-webrtc"]

[dependencies]
mr_server_lib = { path = "../../libs/server_lib" }

bevy = { version = "0.5", default-features = false }
env_logger = "0.8.1"
rymder = "0.2.2"
sentry = "0.21.0"
tokio = "1.12.0"
