on:
  push:
    branches: [main]
    paths-ignore:
      - 'k8s'
      - '.rustfmt.toml'
      - 'LICENSE'
      - 'README.md'
      - 'wasm-pack.dockerfile'

name: Build and publish

concurrency:
  group: Build
  cancel-in-progress: true

jobs:
  mr_matchmaker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mr_matchmaker.dockerfile
          push: true
          tags: mvlabat/mr_matchmaker:latest,mvlabat/mr_matchmaker:${{ github.sha }}
          cache-from: type=registry,ref=mvlabat/mr_matchmaker:buildcache
          cache-to: type=registry,ref=mvlabat/mr_matchmaker:buildcache,mode=max

  mr_persistence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mr_persistence.dockerfile
          push: true
          tags: mvlabat/mr_persistence:latest,mvlabat/mr_persistence:${{ github.sha }}
          cache-from: type=registry,ref=mvlabat/mr_persistence:buildcache
          cache-to: type=registry,ref=mvlabat/mr_persistence:buildcache,mode=max
          build-args: |
            muddle_auth0_client_id=${{ secrets.MUDDLE_AUTH0_CLIENT_ID }}
            muddle_google_web_client_id=${{ secrets.MUDDLE_GOOGLE_WEB_CLIENT_ID }}
            muddle_google_desktop_client_id=${{ secrets.MUDDLE_GOOGLE_DESKTOP_CLIENT_ID }}

  mr_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mr_server.dockerfile
          push: true
          tags: mvlabat/mr_server:latest,mvlabat/mr_server:${{ github.sha }}
          cache-from: type=registry,ref=mvlabat/mr_server:buildcache
          cache-to: type=registry,ref=mvlabat/mr_server:buildcache,mode=max
          build-args: |
            muddle_auth0_client_id=${{ secrets.MUDDLE_AUTH0_CLIENT_ID }}
            muddle_google_web_client_id=${{ secrets.MUDDLE_GOOGLE_WEB_CLIENT_ID }}
            muddle_google_desktop_client_id=${{ secrets.MUDDLE_GOOGLE_DESKTOP_CLIENT_ID }}

  mr_web_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mr_web_client.dockerfile
          push: true
          tags: mvlabat/mr_web_client:latest,mvlabat/mr_web_client:${{ github.sha }}
          cache-from: type=registry,ref=mvlabat/mr_web_client:buildcache
          cache-to: type=registry,ref=mvlabat/mr_web_client:buildcache,mode=max
          build-args: |
            muddle_matchmaker_url=ws://muddle.run:8080
            muddle_public_persistence_url=http://muddle.run:8082
            sentry_dsn=${{ secrets.SENTRY_DSN_CLIENT }} # a client secret is not a secret really, but nvm :)
            muddle_auth0_client_id=${{ secrets.MUDDLE_AUTH0_CLIENT_ID }}
            muddle_google_client_id=${{ secrets.MUDDLE_GOOGLE_WEB_CLIENT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [mr_matchmaker, mr_persistence, mr_server, mr_web_client]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Configure kubectl
        run: echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > /tmp/kube_config

      - name: Deploy mr_matchmaker
        env:
          KUBECONFIG: /tmp/kube_config
        run: kubectl set image deployment mr-matchmaker mr-matchmaker=mvlabat/mr_matchmaker:${{ github.sha }}

      - name: Deploy mr_persistence
        env:
          KUBECONFIG: /tmp/kube_config
        run: kubectl set image deployment mr-persistence mr-persistence=mvlabat/mr_persistence:${{ github.sha }}

      - name: Deploy mr_web_client
        env:
          KUBECONFIG: /tmp/kube_config
        run: kubectl set image deployment mr-web-client mr-web-client=mvlabat/mr_web_client:${{ github.sha }}
